services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap -ui -client 0.0.0.0 -data-dir /consul/data -config-dir consul/config"
    volumes:
      - ./backend/docker/data/consul/data:/consul/data
      - ./backend/docker/data/consul/config:/consul/config

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - consul
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - consul
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  product-service:
    build: ./backend/product-service
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - consul

  cart-service:
    build: ./backend/cart-service
    ports:
      - "3003:3003"
    restart: always
    depends_on:
      - consul

  order-service:
    build: ./backend/order-service
    ports:
      - "3004:3004"
    restart: always
    depends_on:
      - consul

  payment-service:
    build: ./backend/payment-service
    ports:
      - "3005:3005"
    depends_on:
      - consul
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  notification-service:
    build: ./backend/notification-service
    ports:
      - "3006:3006"
    restart: always
    depends_on:
      - consul
